modLoader = "javafml"
loaderVersion = "[${fmlloader_version},${next_fmlloader_version})"
license = "${sinoseries_license}"
issueTrackerURL = "${sinoseries_issues}"

[[mods]]
modId = "sinotest"

version = "${version}"
displayName = "${mod_name}"
displayURL = "${sinoseries_url}"
credits = "${sinoseries_credits}"
authors = "${sinoseries_authors}"

description = '''
A test mod for SinoSeries.
华夏系列开发环境测试模组。
'''

[[dependencies.sinotest]]
modId = "forge"
mandatory = true
versionRange = "[${fmlloader_version},${next_fmlloader_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinotest]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},${next_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinotest]]
modId = "sinofoundation"
mandatory = true
versionRange = "[${sinoseries_full_version},${next_sinoseries_full_version})"
ordering = "AFTER"
side = "BOTH"
