modLoader = "javafml"
loaderVersion = "[${fmlloader_version},${next_fmlloader_version})"
license = "${sinoseries_license}"
issueTrackerURL = "${sinoseries_issues}"

[[mods]]
modId = "sinofoundation"

version = "${version}"
displayName = "${mod_name}"
displayURL = "${sinoseries_url}"
credits = "${sinoseries_credits}"
authors = "${sinoseries_authors}"

description = '''
Foundation contents of SinoSeries mods.
华夏系列基础内容。
'''

[[dependencies.sinofoundation]]
modId = "forge"
mandatory = true
versionRange = "[${fmlloader_version},${next_fmlloader_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinofoundation]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},${next_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinofoundation]]
modId = "sinocore"
mandatory = true
versionRange = "[${sinoseries_full_version},${next_sinoseries_full_version})"
ordering = "AFTER"
side = "BOTH"
