width = 512
height = 256

selected = [22, 140]

# Texture background
[background]
type = "texture"
size = [212, 256]

# Player inventory
[inventory]
type = "slots"
count = [3, 9]
position = [42, 171]
[selection_bar]
type = "slots"
count = 9
position = [42, 229]

# Canvas
[canvas]
type = "texture"
size = [130, 130]
uv = [212, 0]
position = [58, 11]
[shadow]
type = "texture"
size = [130, 130]
uv = [342, 0]
position = [58, 11]

# ColorPal
[color_selector]
type = "texture"
size = [18, 138]
uv = [472, 0]
position = [13, 73]
[color]
type = "texture"
size = [8, 8]
uv = [288, 144]

# Item slot
[paper]
type = "slot"
position = [14, 17]
[ink]
type = "slot"
position = [14, 39]
[result]
type = "slot"
position = [14, 225]

[output_button_texture]
type = "texture"
size = [14, 14]
uv = [256, 144]
[copy_button_texture]
type = "texture"
size = [14, 14]
uv = [272, 144]

[copy_button]
type = "button"
size = [14, 14]
position = [192, 111]
texture = "copy_button_texture"
tooltip = "sinocalligraphy.gui.brush.button.copy.tooltip"

[output_button]
type = "button"
size = [14, 14]
position = [192, 127]
texture = "output_button_texture"
tooltip = "sinocalligraphy.gui.brush.button.output.tooltip"

[draw_button_texture]
type = "texture"
size = [16, 16]
uv = [256, 176]
[draw_button_over_texture]
type = "texture"
size = [16, 16]
uv = [272, 176]
[draw_button_disable_texture]
type = "texture"
size = [16, 16]
uv = [288, 176]
[draw_button_press_texture]
type = "texture"
size = [16, 16]
uv = [304, 176]

[draw_button_yes_texture]
type = "texture"
size = [16, 16]
uv = [320, 176]
position = [172, 148]
[draw_button_no_texture]
type = "texture"
size = [16, 16]
uv = [336, 176]
position = [172, 148]

[draw_apply_button]
type = "button"
position = [172, 148]
size = [16, 16]
texture = ["draw_button_yes_texture", "draw_button_texture"]
texture_hover = ["draw_button_yes_texture", "draw_button_over_texture"]
texture_pressed = ["draw_button_yes_texture", "draw_button_press_texture"]
texture_disable = ["draw_button_yes_texture", "draw_button_disable_texture"]
tooltip = "sinocalligraphy.gui.brush.button.apply.tooltip"

[draw_clear_button]
type = "button"
position = [188, 148]
size = [16, 16]
texture = ["draw_button_no_texture", "draw_button_texture"]
texture_hover = ["draw_button_no_texture", "draw_button_over_texture"]
texture_pressed = ["draw_button_no_texture", "draw_button_press_texture"]
texture_disable = ["draw_button_no_texture", "draw_button_disable_texture"]
tooltip = "sinocalligraphy.gui.brush.button.clear.tooltip"

[draw_title_box_texture]
type = "texture"
size = [128, 16]
uv = [256, 160]
position = [41, 148]

[draw_name]
type = "editbox"
position = [43, 150]
size = [128, 16]
title = "sinocalligraphy.gui.narration.brush.title_box"
color = 0xFFFFFF
bordered = false
max_length = 50

