width = 256
height = 256

[title]
type = "text"
position = [58, 71]

[background]
type = "texture"
size = [176, 166]

[fire]
type = "texture"
size = [14, 14]
uv = [176, 0]

[arrow]
type = "texture"
size = [24, 17]
uv = [176, 14]

[btn_normal]
type = "texture"
size = [21, 21]
uv = [176, 31]

[btn_hover]
type = "texture"
size = [21, 21]
uv = [176, 52]

[btn_pressed]
type = "texture"
size = [21, 21]
uv = [176, 73]

[firing]
type = "progress"
position = [57, 36]
texture_filled = "fire"
direction = "-vertical"

[burning]
type = "progress"
position = [79, 34]
texture_filled = "arrow"

[button]
type = "button"
size = [21, 21]
position = [5, 5]
texture = "btn_normal"
texture_hover = "btn_hover"
texture_pressed = "btn_pressed"
tooltip = "Hi~~~"

[input]
type = "slot"
position = [55, 16]

[matel]
type = "slot"
position = [55, 52]

[output]
type = "slot"
position = [111, 30]
size = 25

[inventory]
type = "slots"
count = [3, 9]
position = [7, 83]

[selection]
type = "slots"
count = 9
position = [7, 141]
