modLoader = "javafml"
loaderVersion = "[${fmlloader_version},${next_fmlloader_version})"
license = "All Rights Reserved"

[[mods]]
modId = "sinocalligraphy"

version = "${version}"
displayName = "${mod_name}"
displayURL = "${sinoseries_url}"
credits = "${sinoseries_credits}"
authors = "${sinoseries_authors}"

description = '''
The painting that used color to depict all walks of life, while retained black and white to render the beauty of ages.
丹青描绘浮生，云墨书尽芳华。
'''

[[dependencies.sinocalligraphy]]
modId = "forge"
mandatory = true
versionRange = "[${fmlloader_version},${next_fmlloader_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinocalligraphy]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},${next_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinocalligraphy]]
modId = "sinofoundation"
mandatory = true
versionRange = "[${sinoseries_full_version},${next_sinoseries_full_version})"
ordering = "NONE"
side = "BOTH"
