modLoader = "javafml"
loaderVersion = "[${fmlloader_version},${next_fmlloader_version})"
license = "All Rights Reserved"

[[mods]]
modId = "sinofeast"

version = "${version}"
displayName = "${mod_name}"
displayURL = "${sinoseries_url}"
credits = "${sinoseries_credits}"
authors = "${sinoseries_authors}"

description = '''
This grand banquet is just for you.
这盛大的宴会只为你准备。
'''

[[dependencies.sinofeast]]
modId = "forge"
mandatory = true
versionRange = "[${fmlloader_version},${next_fmlloader_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinofeast]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},${next_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.sinofeast]]
modId = "sinocore"
mandatory = true
versionRange = "[${sinoseries_full_version},${next_sinoseries_full_version})"
ordering = "NONE"
side = "BOTH"
